# Generated by Django 4.2.20 on 2025-05-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="updated_at",
        ),
    ]
