# Generated by Django 4.2.20 on 2025-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
