# Generated by Django 4.2.20 on 2025-04-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="order",
        ),
    ]
