# Generated by Django 4.2.20 on 2025-04-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("sales", "0002_remove_sale_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="orders.order",
            ),
        ),
    ]
