# Generated by Django 4.2.20 on 2025-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2025-05-03 16:25:30.672992+03",
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
