# Generated by Django 4.2.20 on 2025-05-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
            },
        ),
        migrations.AlterModelTable(
            name="purchaseorder",
            table="purchase_order",
        ),
        migrations.AlterModelTable(
            name="purchaseorderitem",
            table="purchase_order_item",
        ),
    ]
