# Generated by Django 4.2.20 on 2025-05-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("supplier", "0002_alter_purchaseorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.product"
            ),
        ),
    ]
